// Design system — componentes reutilizáveis. Importe sempre daqui:
//   import { BaseButton, PageHeader } from '@/shared/components/ui'
// Guia: frontend/docs/design-system.md
export { default as AlertContainer } from './AlertContainer.vue'
export { default as BaseAlert } from './BaseAlert.vue'
export { default as BaseBadge } from './BaseBadge.vue'
export { default as BaseButton } from './BaseButton.vue'
export { default as BaseCard } from './BaseCard.vue'
export { default as BaseCheckbox } from './BaseCheckbox.vue'
export { default as BaseField } from './BaseField.vue'
export { default as BaseIcon } from './BaseIcon.vue'
export { default as BaseInput } from './BaseInput.vue'
export { default as BaseModal } from './BaseModal.vue'
export { default as BaseProgress } from './BaseProgress.vue'
export { default as BaseSelect } from './BaseSelect.vue'
export { default as BaseSpinner } from './BaseSpinner.vue'
export { default as BaseSwitch } from './BaseSwitch.vue'
export { default as BaseTable } from './BaseTable.vue'
export { default as BaseTabs } from './BaseTabs.vue'
export { default as BaseTextarea } from './BaseTextarea.vue'
export { default as ConfirmModal } from './ConfirmModal.vue'
export { default as EmptyState } from './EmptyState.vue'
export { default as PageContainer } from './PageContainer.vue'
export { default as PageHeader } from './PageHeader.vue'
export { default as StatCard } from './StatCard.vue'

export { icons, statusIcons, type IconName, type StatusVariant } from './icons'
export type { SelectOption } from './BaseSelect.vue'
export type { TableColumn } from './BaseTable.vue'
export type { TabItem } from './BaseTabs.vue'
